title: John Doe # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I analyze customer data to solve business problems and address leadership's needs. Skilled in predictive modeling, data wrangling, data visualization, public speaking and leading cross-functional working groups. Current M.S. in Business Analytics student at the University of Virginia. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/adrian-sanchez-lemoine/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
